# Generated by Django 3.1.7 on 2021-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HocTap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSSV', models.CharField(max_length=10)),
                ('HOTEN', models.CharField(max_length=50)),
                ('LOP', models.CharField(max_length=50)),
                ('SDT', models.IntegerField(max_length=10)),
            ],
        ),
    ]
